### ISSUE TITLE
USE PDO

### ISSUE THREAD

**Issue by biggerbraintime** [the-real-sumsome/subrocks-2012#2]
MYSQLI IS FUCKING DISGUSTING

**Comment by biggerbraintime** [comment]
ok i decided to convert the codebase to pdo, please dont fucking commit thx

**Comment by the-real-sumsome** [comment]
can u make a pr

**Comment by biggerbraintime** [comment]
> can u make a pr

im not done yet

**Comment by biggerbraintime** [comment]
#3
