### ISSUE TITLE
Alt account detection blocks signups when attempted on a localhost server

### ISSUE THREAD

**Issue by SoulRepo** [the-real-sumsome/subrocks-2012#36]
When I attempt to make an account on a localhost setup, it fails and throws this error:
` Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ip' in 'where clause' in /var/www/html/public/d/signup.php:55 Stack trace: #0 /var/www/html/public/d/signup.php(55): PDO->prepare('SELECT * FROM u...') #1 {main} thrown in /var/www/html/public/d/signup.php on line 55`

**Comment by pixdoet** [comment]
try accessing it from 127.0.0.1

**Comment by SoulRepo** [comment]
Just shows the Apache2 default page

**Comment by the-real-sumsome** [comment]
the SQL that you import is outdated and that's an issue that is caused by me, new commit

**Comment by the-real-sumsome** [comment]
fixes the issue
