### ISSUE TITLE
Video uploading stuck at 100%. PHP Error log appears in Network tab.

### ISSUE THREAD

**Issue by LushPineapple29** [the-real-sumsome/subrocks-2012#48]
I just set up a Docker instance with a NGINX Reverse proxy making it available on Port 443.
When I upload a Video, It will get stuck at 100% and the Network tab will produce a log with this.
`<br />
<b>Warning</b>:  move_uploaded_file(../dynamic/temp/DQ6U7JeLiDU.mp4): Failed to open stream: Permission denied in <b>/var/www/html/public/d/upload.php</b> on line <b>50</b><br />
<br />
<b>Warning</b>:  move_uploaded_file(): Unable to move &quot;/tmp/phpTk0hrS&quot; to &quot;../dynamic/temp/DQ6U7JeLiDU.mp4&quot; in <b>/var/www/html/public/d/upload.php</b> on line <b>50</b><br />
Failed to move temp file to dynamic folder. Pottential IO/permission problem.0`

It may be a Permission issue but I don't know the solution, I'm not too great at Docker. If anyone could help I would be really thankful.

-LushPineapple29

**Comment by Yosh1002** [comment]
same error.

**Comment by Hwilliams8548** [comment]
chmod it

**Comment by Yosh1002** [comment]
> chmod it
with what?

**Comment by LushPineapple29** [comment]
This issue was not related to permissions, I found the solution but It was so long ago that I forgot. I also shut down the instance today so..... o_O.
