### ISSUE TITLE
PDOException when hosting, can't connect to PHPMyAdmin

### ISSUE THREAD

**Issue by pixdoet** [the-real-sumsome/subrocks-2012#6]
Whenever I host an instance of subrocks this happens:
`PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/html/public/s/classes/config.inc.php:37 Stack trace: #0 /var/www/html/public/s/classes/config.inc.php(37): PDO->__construct('mysql:host=loca...', 'root', 'root', Array) #1 /var/www/html/public/index.php(78): require_once('/var/www/html/p...') #2 {main}`
I have tried changing the host to localhost, 127.0.0.1 and etc. None of them worked.
Also I can't connect to PHPMyAdmin as well.

**Comment by pixdoet** [comment]
I put both of them at the start of `config.inc.php` and it's still producing the same results. Am I supposed to put it somewhere else?

**Comment by the-real-sumsome** [comment]
Go `git pull`

Check the new README, there are some new instructions on how to import the DB. Go to http://localhost:8080 and import the SQL file from `sql_setup`.

**Comment by nintendo-gif** [comment]
That's because it needs to be either "%" or "localhost"

**Comment by the-real-sumsome** [comment]
Are you using Docker? If so, are you using `docker-compose up -d` & do you see MySQL outputting anything with `docker-compose logs -f`?

**Comment by pixdoet** [comment]
Yes, I'm using docker and `docker-compose up -d` Apparently the MySQL server shut down? Here's the output of `docker-compose logs -f`:
```
mysql                     | 2021-10-18 02:21:46+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.21 started.
mysql                     | 2021-10-18 02:21:46+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql                     | 2021-10-18 02:21:46+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.21 started.
mysql                     | 2021-10-18 02:21:46+00:00 [Note] [Entrypoint]: Initializing database files
mysql                     | mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (OS errno 13 - Permission denied)
mysql                     | 2021-10-18T02:21:46.899037Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.21) initializing of server in progress as process 43
mysql                     | 2021-10-18T02:21:46.901538Z 0 [ERROR] [MY-010460] [Server] --initialize specified but the data directory exists and is not writable. Aborting.
mysql                     | 2021-10-18T02:21:46.901544Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
mysql                     | 2021-10-18T02:21:46.901725Z 0 [ERROR] [MY-010119] [Server] Aborting
mysql                     | 2021-10-18T02:21:46.901853Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.21)  MySQL Community Server - GPL.

```

**Comment by pixdoet** [comment]
> might be because of the pdo extension not being initialised, go to php.ini and add extension=pdo_mysql
Nope, still isn't. The problem seems to lie within some sort of permission error though. 
`mysql                     | mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (OS errno 13 - Permission denied)`
This line might be the cause of the error, though I'm not sure what is it that it cannot access right now. I've tried `chown`ing the `data` folder to `mysql:mysql` but it still doesn't seem to work.

**Comment by pixdoet** [comment]
`sudo` creates more problems with docker, plus macos doesn't have `usermod` lol ripbozo.
Anyways this is driving me crazy. For the moment I'll just use a Linux VM or something. Do I just close this issue or what?

**Comment by pixdoet** [comment]
Alright, I guess we'll leave this up to the people that have more knowledge on MacOS and Docker.
